---
title: Frank Condezo
description: Software Engineer
domain: https://condef5.com
language: en
repository: https://github.com/condef5/personal-site/
email: frankcondezo@gmail.com
social:
  twitter: condef5
  github: condef5
  npm: condef5
  linkedin: condef5
  dev: condef5
  meetup: 217133732
navigation:
  - name: Bio
    path: /bio/
incremental: false
icon: /static/favicon@48.png
