---
title: Frank Condezo
description: FullStack Software Engineer and Addicted to manga
domain: https://banzai.dev
language: en
social:
  twitter: condef5
  github: condef5
  linkedin: condef5
  dev: condef5
  meetup: 217133732
navigation:
  - name: Bio
    path: /bio/
